fullname: Apery
shortname: apery
organization: math-comp
opam_name: coq-mathcomp-apery
community: false
action: true
coqdoc: false

synopsis: >-
  A formally verified proof, by computer algebra, that ζ(3) is irrational

description: |-
  This project contains a formal proof that the real number zeta(3),
  also known as Apéry's constant, is irrational. It follows roughly
  Apéry's original sketch of a proof. However, the recurrence
  relations constituting the crux of the proof have been guessed by a
  computer algebra program (in this case in Maple/Algolib). These
  relations are formally checked a posteriori, so that Coq's kernel
  remains the sole trusted code base.

publications:
- pub_url: https://arxiv.org/abs/1912.06611
  pub_title: A Formal Proof of the Irrationality of ζ(3)
- pub_url: https://software.imdea.org/~aleks/papers/reflect/reflect.pdf
  pub_title: A Computer-Algebra-Based Formal Proof of the Irrationality of ζ(3)
  pub_doi: 10.1007/978-3-319-08970-6_11

authors:
- name: Frédéric Chyzak
  initial: true
- name: Assia Mahboubi
  initial: true
- name: Thomas Sibut-Pinote
  initial: true

opam-file-maintainer: assia.mahboubi@inria.fr

opam-file-version: dev

license:
  fullname: CeCILL-C
  identifier: CECILL-C
  file: Licence_CeCILL-C_V1-en.txt

supported_coq_versions:
  text: 8.11 or later
  opam: '{(>= "8.11" & < "8.15~") | (= "dev")}'

tested_coq_opam_versions:
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.11'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.12'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.14'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.12" & < "1.14~") | (= "dev")}'
  description: |-
    [MathComp ssreflect 1.12 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
  description: |-
    [MathComp field](https://math-comp.github.io)
- opam:
    name: coq-coqeal
    version: '{>= "1.0.5"}'
  description: |-
    [CoqEAL 1.0.5 or later](https://github.com/CoqEAL/CoqEAL)
- opam:
    name: coq-mathcomp-real-closed
    version: '{>= "1.1.2"}'
  description: |-
    [MathComp real closed fields 1.1.2 or later](https://github.com/math-comp/real-closed)
- opam:
    name: coq-mathcomp-bigenough
    version: '{>= "1.0.0"}'
  description: |-
    [MathComp bigenough 1.0.0 or later](https://github.com/math-comp/bigenough)

namespace: mathcomp.apery

keywords:
- name: apery recurrence
- name: irrationality
- name: creative telescoping

categories:
- name: Math/Arith/Number theory
